package org.omri.tuner;

public enum TunerStatus {
    TUNER_STATUS_NOT_INITIALIZED,
    TUNER_STATUS_INITIALIZED,
    TUNER_STATUS_SUSPENDED,
    TUNER_STATUS_SCANNING,
    TUNER_STATUS_ERROR,
    SERVICES_LIST_READY,
    VISUALS_LIST_READY
}
