package org.omri.radioservice.metadata;

public enum TextualType {
    METADATA_TEXTUAL_TYPE_DAB_DLS,
    METADATA_TEXTUAL_TYPE_DAB_DLS_PLUS,
    METADATA_TEXTUAL_TYPE_FM_RDS_RADIOTEXT,
    METADATA_TEXTUAL_TYPE_IP_ICY,
    METADATA_TEXTUAL_TYPE_IP_RDNS_RADIOVIS
}
