package org.omri.radioservice.metadata;

public enum VisualMimeType {
    METADATA_VISUAL_MIMETYPE_UNKNOWN,
    METADATA_VISUAL_MIMETYPE_JPEG,
    METADATA_VISUAL_MIMETYPE_PNG,
    METADATA_VISUAL_MIMETYPE_GIF,
    METADATA_VISUAL_MIMETYPE_BMP,
    METADATA_VISUAL_MIMETYPE_SVG
}
